### ISSUE TITLE
www: Remove all mentions of PDUs, DCPM and ACL Series

### ISSUE THREAD

**Issue by pvanlaet** [racktivity/www-racktivity#4]
All mentions of the PDUs and DCPM need to be removed from the website:
Here is a starting overview on what needs to be done:
- REMOVE: http://racktivity.com/products/power-management-software/
- REMOVE: http://racktivity.com/products/power-management-software/dcpm/
- REMOVE: http://racktivity.com/products/rack-power-management/
- REMOVE: http://racktivity.com/products/rack-power-management/pm0816-01/
- REMOVE: http://racktivity.com/products/rack-power-management/es1108-16-euk-euuk/
- REMOVE: http://racktivity.com/products/rack-power-management/es1108-16-us-us/
- REMOVE: http://racktivity.com/products/rack-power-management/es2124-32-1-phase-32a/
- REMOVE: http://racktivity.com/products/rack-power-management/es2124-30-1-phase-30a-us/
- REMOVE: http://racktivity.com/products/rack-power-management/es2224-32-1-phase-32a/
- REMOVE: http://racktivity.com/products/rack-power-management/es6124-16-3-phase-16a/
- REMOVE: http://racktivity.com/products/rack-power-management/es6124-32-3-phase-32a/
- REMOVE: http://racktivity.com/products/rack-power-management/es6224-16-3-phase-16a/
- REMOVE: http://racktivity.com/products/rack-power-management/es6224-32-3-phase-32a/
- REMOVE: http://racktivity.com/products/rack-power-management/es8000-flex-pdu/
- REMOVE: http://racktivity.com/resources/racktivity's-energy-dna/
- REMOVE: http://racktivity.com/products/infrastructure-power-management/acl-series/
- REMOVE: http://racktivity.com/products/infrastructure-power-management/acl-master/
- REMOVE: http://racktivity.com/products/infrastructure-power-management/acl-slave/
- REMOVE: http://racktivity.com/products/infrastructure-power-management/acld-display/
- REMOVE: "Power management software" and "Rack power management" from footer 'Quick-links'
- REMOVE: "DCPM - Power Management Software" and "ES PDU Series - Rack power management" sections/rectangles from the home page
- REMOVE: "EnergyDNA™" section from the home page
- REMOVE: "Did you know?" top banner from the home page
- REPLACE: top banner product image from http://racktivity.com/company/
- REPLACE: top banner product image from http://racktivity.com/support/
- REPLACE: top banner product image from http://racktivity.com/racktivity-warranty/
- REPLACE: top banner product image from http://racktivity.com/news/new-ceo-greenitglobe/
- REPLACE: top banner product image from http://racktivity.com/contact/
- REPLACE: top banner product image from http://racktivity.com/resources/modern-lexicon/
- REPLACE: top banner product image from http://racktivity.com/partners/
- REPLACE: top banner product image from http://racktivity.com/partner-information/
- REPLACE: top banner product image from http://racktivity.com/customers/

**Comment by JacqTrade** [comment]
PDU's are required by GIG - do not remove
